### ISSUE TITLE
Handle AS23456 properly

### ISSUE THREAD

**Issue by htj** [job/irrexplorer#27] opened 2015-06-09 13:34 UTC
For instance:

http://irrexplorer.nlnog.net/prefix/80.210.80.0/20

I am not exactly sure what the solution here is. Is it safe to simply ignore anything with AS23456?

**Comment by job** [comment] 2015-06-09 14:24
I have depreffed AS 23456 paths in the Looking Glass, that might provide better input to irrexplorer: https://github.com/NLNOG/ring-puppet/commit/615253b7fb79993e9391a583f2713c599f68a7c2 however if there is only one path and that is originated by someonse using 23456, it is what it is I think.

We could highlight as a new error message "Warning: no 32-bit ASNs are not properly supported somewhere, plz investigate and fix!"

**Comment by job** [comment] 2015-06-09 20:24
Turns out the specific example you used were fake paths injected by a "BGP optimiser". That feed towards the NLNOG RING LG has been shutdown for now because it doesn't provide "DFZ" information.

Combined with the lower local pref for 23456 routes I think we should see if this issue pops up again and assess what the cause is. Closing for now.

**Closed as completed by job** 2015-06-09 20:24 UTC

**Comment by htj** [comment] 2015-06-12 20:31
For future reference. This is the list of special AS numbers that may be require special treatment:
http://www.iana.org/assignments/iana-as-numbers-special-registry/iana-as-numbers-special-registry.xhtml
